FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3 python3-pip git
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /app
COPY docker/requirements_api.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements_api.txt

COPY app ./app
CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]
HEALTHCHECK --interval=10s --timeout=5s --retries=10 \
  CMD curl -f http://localhost:8000/health || exit 1
