FROM python:3.10

WORKDIR /ui
COPY docker/requirements_ui.txt .
RUN pip install --no-cache-dir -r requirements_ui.txt

COPY . .
CMD ["streamlit", "run", "ui/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
